-- Autogenerated by Luapress v3.0
-- For available configuation options, see: fizzadar.com/luapress
-- Or see the default config at:
-- github.com/Fizzadar/Luapress/blob/develop/luapress/default_config.lua

local config = {
    url = '/tests/index/build',
    index_page = 'home',
    force_index_page = true
}

return config
