-- Generated by Luapress v3.0
-- envs table added

local config = {
    envs = {
        dev = {
            url = '/tests/envs/another_build',
            build_dir = 'another_build'
        },
        default = {
            url = '/tests/envs/build',
            build_dir = 'build'
        }
    }
}

return config
