-- Generated by Luapress v3.0
-- pages_dir and posts_dir added

local config = {
    url = '/tests/directories/build',
    posts_dir = 'post',
    pages_dir = 'page',
    archive_title = 'Old Posts'
}

return config
