-- Autogenerated by Luapress
local config = {
    -- Blog base url
    url = '/tests/directories/build',
    -- Blog title
    title = 'Luapress directories test',
    -- Template name
    template = 'default',
    -- Posts per page
    posts_per_page = 2,
    -- Link directories not files
    link_dirs = true,
    pages_dir = 'page',
    posts_dir = 'post',
    -- Separator to put inside <a id="more"></a> link
    more_separator = '',
    -- Select a page as the landing page (optional, no path or suffix)
    index = nil,
}

return config
